version: '3.9'

services:
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
    environment:
     - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    volumes:
      - ./backend/:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    # ports:
    #   - 8000:8000
    command: ./start.sh
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frank
      - POSTGRES_PASSWORD=password_dev
      - POSTGRES_DB=database_dev

  nginx:
    restart: always
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  postgres_data:
  static_volume:
  media_volume: